# Generated by Django 2.0.3 on 2018-06-06 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0011_auto_20180606_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 6, 6, 18, 1, 15, 993671)),
        ),
    ]
