# Generated by Django 2.0.3 on 2018-06-08 04:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sampleapp', '0017_auto_20180607_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(db_index=True, default=datetime.datetime(2018, 6, 8, 10, 27, 31, 780582))),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_music', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 6, 8, 10, 27, 31, 780582)),
        ),
    ]
