# Generated by Django 2.0.3 on 2018-06-08 07:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0021_auto_20180608_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='sampleapp.Room'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 6, 8, 12, 47, 54, 478383)),
        ),
        migrations.AlterField(
            model_name='musicpiece',
            name='created',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 6, 8, 12, 47, 54, 479381)),
        ),
    ]
